1er pull request
carlosjimenez88M/Github-Class pull request #2
Opened 2020-10-13 00:36 UTC by ECortina

2020-10-13 00:47 UTC, carlosjimenez88M commented
Los cambios tiene conflictos

2020-10-14 16:09 UTC, ECortina reviewed
cambios clase 2 intro analitica, code2 y readme

2020-10-14 22:01 UTC, carlosjimenez88M requested changes
Este código tiene coblficto

2020-10-14 22:07 UTC, ECortina reviewed
add nombre

2020-10-14 22:07 UTC, ECortina commented on README.md
> +
adición nombre profesor

2020-10-18 18:02 UTC, carlosjimenez88M commented on Presentations/Clase2code.Rmd
> +
Kike porfa explica acá porque haces esto

2020-10-18 18:02 UTC, carlosjimenez88M commented on Presentations/Clase2code.Rmd
> +Graficar el conteo de palabras
Toca colocar esto como un titulo

2020-10-18 18:02 UTC, carlosjimenez88M commented on Presentations/Clase2code.Rmd
> +
Puedes usar la función reorder para que quede más bacana la gráfica

2020-10-18 18:02 UTC, carlosjimenez88M commented on Presentations/Clase2code.Rmd
> +imdb_data<- read.csv("IMDB-movies.csv")
¿Donde está la data? Porfa sube la data al repo, créate una carpeta con los datos, y así lo podemos trabajar más fácil

2020-10-20 03:51 UTC, ECortina reviewed
cambio clase , presentacion y md

2020-10-20 03:52 UTC, merged